<a href="https://colab.research.google.com/github/Aadi-88-shah/Outfitrecommender/blob/main/P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# prompt: print addition subtraction multiplication and division of two matrices

import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Addition
sum_matrix = matrix1 + matrix2
print("Addition:")
print(sum_matrix)

# Subtraction
diff_matrix = matrix1 - matrix2
print("\nSubtraction:")
print(diff_matrix)

# Multiplication (Element-wise)
prod_matrix_elementwise = matrix1 * matrix2
print("\nElement-wise Multiplication:")
print(prod_matrix_elementwise)

# Matrix Multiplication (Dot product)
prod_matrix_dot = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication (Dot product):")
print(prod_matrix_dot)

# Division (Element-wise)
# To avoid division by zero, we might need to handle cases where elements in matrix2 are zero.
# For simplicity here, we assume no zero elements in matrix2.
div_matrix = matrix1 / matrix2
print("\nElement-wise Division:")
div_matrix

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication (Dot product):
[[19 22]
 [43 50]]

Element-wise Division:


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])